from redis_om import HashModel

class ProjectCache(HashModel):
    project_id: str
    project_title: str
    creation_time: str
    production_time: str
    in_production: str
    project_language: str
    purpose: str
    purpose_other: str
    project_notes: str
    custom_record_label: str
    secondary_unique_field: str
    is_longitudinal: str
    has_repeating_instruments_or_events: str
    surveys_enabled: str
    scheduling_enabled: str
    record_autonumbering_enabled: str
    randomization_enabled: str
    ddp_enabled: str
    project_irb_number: str
    project_grant_number: str
    project_pi_firstname: str
    project_pi_lastname: str
    display_today_now_button: str
    missing_data_codes: str
    external_modules: str
    bypass_branching_erase_field_prompt: str

class REDCapReportStudyDashboardCache(HashModel):
    dm: str
    record_id: str
    siteid: str
    genderid: str
    genderidot: str
    scrsex: str
    scrsexot: str
    race: str
    raceot: str
    race2: str
    ethnic: str
    ethnicot: str
    ancestry: str
    recstartts: str
    reccmpts: str
    reccmpdat: str
    faqstartts: str
    faqcmpts: str
    faqcmpdat: str
    scrstartts: str
    scrcmpts: str
    scrcmpdat: str
    preconstartts: str
    preconcmpts: str
    preconcmpdat: str
    icfsvyts: str
    icfcmpts: str
    icf_dat: str
    icfa_dat: str
    prtcmpdat: str
    dmgstartts: str
    dmgcmpts: str
    dmgcmpdat: str
    mhstartts: str
    mhcmpts: str
    mhcmpdat: str
    sustartts: str
    sucmpts: str
    sucmpdat: str
    cesstartts: str
    cescmpts: str
    cesmpdat: str
    paidstartts: str
    paidcmpts: str
    paidcmpdat: str
    dmlstartts: str
    dmlcmpts: str
    dmlcmpdat: str
    dietstartts: str
    dietcmpts: str
    dietcmpdat: str
    viastartts: str
    viacmpts: str
    viacmpdat: str
    pxsdohstartts: str
    pxsdohcmpts: str
    pxsdohcmpdat: str
    pxfistartts: str
    pxsficmpts: str
    pxsficmpdat: str
    pxnestartts: str
    pxnecmpts: str
    pxnecmpdat: str
    pxrdcmpts: str
    pxrdstartts: str
    pxrdcmpdat: str
    declinestartts: str
    declinecmpts: str
    deccmpdat: str
    cnct_sccs: str
    cnct_type: str
    cnct_prp: str
    dvenvyn: str
    dvenvstdat: str
    dvenvreasn: str
    dvenvcrcid: str
    dvcgmyn: str
    dvcgmstdat: str
    dvcgmreasn: str
    dvcgmvrfy: str
    dvamwyn: str
    dvamwstdat: str
    dvamwreasn: str
    dvamwsn: str
    dvrtmthd: str
    dvrtnyn: str
    dvrtnship: str
    mhterm_dm1: str
    mhterm_dm2: str
    mhterm_predm: str
    mh_dm_age: str
    mh_a1c: str
    cmtrt_a1c: str
    cmtrt_insln: str
    cmtrt_glcs: str
    cmtrt_lfst: str

class DashboardCache(HashModel):
    name: str
    varname: str
    namespace: str
    endpoint: str

class StudyDashboardCache(DashboardCache):
    gender: str
    sex: str
    race: str
    ethnicity: str
    ancestry: str
    phenotype: str
    a1c: str
    recruitment_status: str
    consent_status: str
    survey_status: str
    communication_status: str
    device_status_es: str
    device_status_cgm: str
    device_status_amw: str
    device_status_all: str
    intervention_status: str
