version: '3'
services:
  flask-api:
    build:
      context: .
      dockerfile: Dockerfile    
    ports:
      - "5000:5000"
    # volumes:
    #   - ./apis:/app/apis
    #   - ./model:/app/model
    #   - ./core:/app/core
    #   - ./app.py:/app/
    #   - ./config.py:/app/
    environment:
      FLASK_ENV: development
      FLASK_DEBUG: 1
      FAIRHUB_DATABASE_URL: "${FAIRHUB_DATABASE_URL:-postgresql://postgres:postgres@database:5432/fairhub}"
  database:
    image: postgres:15.3
    environment:
      - POSTGRES_USER=POSTGRES_USER
      - POSTGRES_PASSWORD=POSTGRES_PASSWORD
      - POSTGRES_DB=POSTGRES_DB
    ports:
      - 5432:5432
    restart: always
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
      - ./sql/init.sql:/docker-entrypoint-initdb.d/1-schema.sql
# volumes:
#   db-data:
