version: '3'
services:
  flask-api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 5000:5000
    # volumes:
    #   - ./apis:/app/apis
    #   - ./model:/app/model
    #   - ./core:/app/core
    #   - ./app.py:/app/
    #   - ./config.py:/app/
    environment:
      FLASK_ENV: development
      FLASK_DEBUG: 1
      FAIRHUB_DATABASE_URL: "${FAIRHUB_DATABASE_URL:-postgresql://postgres:postgres@database:5432/postgres}"
      secret: "mXrkOHXXQoMAhCOTZOV93QlncmeTwEZFPxTP1TXGiOFabE0KmuZgHWvTOLgjbv3S;"
    depends_on:
      database:
        condition: service_healthy
  database:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
      PGUSER: postgres
    ports:
      - 5432:5432
    # restart: always
    healthcheck:
      test: pg_isready
      interval: 10s
      timeout: 5s
      retries: 5
      # volumes:
      #   - ./postgres-data:/var/lib/postgresql/data
      # - ./sql/init_timezones.sql:/docker-entrypoint-initdb.d/1-schema.sql
