version: '3'
services:
  flask-api:
    build:
      context: .
      dockerfile: Dockerfile
    entrypoint:
      - flask
      - run
      - --host=0.0.0.0
      - --port=5000
    ports:
      - 5000:5000
    environment:
      FLASK_DEBUG: 0
      FLASK_APP: ./app.py
      FAIRHUB_DATABASE_URL: "${FAIRHUB_DATABASE_URL}"
      FAIRHUB_SECRET: "${FAIRHUB_SECRET}"
