name: ci

on: [push]

jobs:
  ci:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8"]

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - uses: Gr1N/setup-poetry@v8

      - name: Install dependencies
        run: poetry install

      - uses: actions/cache@v2
        with:
          path: .venv
          key: ${{ runner.os }}-poetry-${{ hashFiles('poetry.lock') }}

      - name: Lint with flake8
        run: poetry run flake8 apis core model app.py

      - name: Type check with mypy
        run: poetry run mypy apis core model app.py

      - name: Link with pylint
        run: poetry run pylint apis core model app.py --rcfile=.pylint.ini
