name: Test

on: [push]

jobs:
  lint:
    name: Run tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10"]
    env:
      # These are simulated secrets for test workflow only.
      FAIRHUB_DATABASE_URL: postgresql://admin:root@localhost:5432/fairhub_local
      FAIRHUB_SECRET: mXrkOHXXQoMAhCOTZOV93QlncmeTwEZFPxTP1TXGiOFabE0KmuZgHWvTOLgjbv3S
      FAIRHUB_CACHE_DEFAULT_TIMEOUT: 86400
      FAIRHUB_CACHE_KEY_PREFIX: fairhub-io#
      FAIRHUB_CACHE_HOST: localhost
      FAIRHUB_CACHE_PORT: 6379
      FAIRHUB_CACHE_DB: fairhub
      FAIRHUB_CACHE_URL: redis://127.0.0.1:6379
      FAIRHUB_CACHE_TYPE: RedisCache

    steps:
      - uses: actions/checkout@v2

      - name: Create a database for tests with docker
        run: docker run --name postgres -p 5432:5432 -e POSTGRES_USER=admin -e POSTGRES_PASSWORD=root -e POSTGRES_DB=fairhub_local -d postgres:latest

      - name: Create a redis instance for tests with docker
        run: docker run --name cache -p 6379:6379 -e CACHE_DB=fairhub -e CACHE_HOST=localhost -e CACHE_PORT=6379 -e CACHE_URL=redis://127.0.0.1:6379 -e CACHE_KEY_PREFIX=fairhub-io# -e CACHE_TIMEOUT=86400 -d redis:7.2-alpine

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - uses: Gr1N/setup-poetry@v8

      - name: Install dependencies
        run: poetry install

      - uses: actions/cache@v2
        with:
          path: .venv
          key: ${{ runner.os }}-poetry-${{ hashFiles('poetry.lock') }}

      - name: Run pytest (with capture)
        run: poetry run pytest -s -W ignore::DeprecationWarning
